### ISSUE TITLE
Troubles with installation

### ISSUE THREAD

**Issue by uebernihilist** [grkek/haki#5]
When i installed shards its simply cleared my disc.
![image](https://user-images.githubusercontent.com/73707238/141451436-153142cd-34fb-4468-9832-28a0e7098f81.png)

**Comment by grkek** [comment]
None of my code has post-install scripts, probably an issue with the shards I use.

**Comment by uebernihilist** [comment]
Oh, i see. I solved the issue. It happen because of Cyrillic.
